-- =====================================================================
-- SISTEMA DE GESTÃO DE BARBEARIAS — ESTRUTURA INICIAL DO BANCO
-- Plataforma: Supabase (PostgreSQL)
-- Como executar: Supabase Dashboard > SQL Editor > colar e rodar.
-- Este arquivo pode ser executado na ordem em que está.
--
-- DECISÕES TÉCNICAS
--   * BIGINT GENERATED BY DEFAULT AS IDENTITY para todas as PKs.
--   * timestamptz para datas/horas; numeric(10,2) para valores monetários.
--   * boolean para campos de ativação (exclusão lógica).
--   * Multi-barbearia desde o início: toda entidade de negócio referencia
--     barbearia_id e as FKs compostas impedem mistura de dados entre barbearias.
--   * updated_at mantido automaticamente por trigger comum (set_updated_at).
--   * Sem ON DELETE CASCADE em relacionamentos de negócio.
--   * RLS habilitado nas tabelas; policies serão criadas na etapa de
--     autenticação (ver roteiro no final do arquivo).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. EXTENSÃO NECESSÁRIA
-- ---------------------------------------------------------------------
-- btree_gist permite usar o operador "=" em colunas bigint dentro de
-- índices GiST. É indispensável para a EXCLUDE constraint que impede
-- agendamentos conflitantes para o mesmo barbeiro (item 9).
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- ---------------------------------------------------------------------
-- 2. FUNÇÃO COMUM PARA ATUALIZAR updated_at
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

-- =====================================================================
-- 3. TABELA: barbearias
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.barbearias (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        TEXT NOT NULL,
    telefone    TEXT,
    email       TEXT,
    endereco    TEXT,
    timezone    TEXT NOT NULL DEFAULT 'America/Sao_Paulo',
    ativo       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_barbearias_email CHECK (
        email IS NULL OR email ~* '^[^@\s]+@[^@\s]+$'
    )
);

-- =====================================================================
-- 4. TABELA: profissionais (perfil vinculado ao Supabase Auth)
-- =====================================================================
-- auth_user_id referencia auth.users(id), com ON DELETE SET NULL: se o
-- login do Supabase for removido, o cadastro do profissional permanece.
-- auth_user_id é opcional e único: permite cadastrar barbeiros sem login
-- e garante que cada usuário autenticado corresponde a 1 profissional.
CREATE TABLE IF NOT EXISTS public.profissionais (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id  UUID REFERENCES auth.users (id) ON DELETE SET NULL,
    barbearia_id  BIGINT NOT NULL,
    nome          TEXT NOT NULL,
    telefone      TEXT,
    cargo         TEXT NOT NULL DEFAULT 'barbeiro',
    ativo         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_profissionais_barbearia
        FOREIGN KEY (barbearia_id) REFERENCES public.barbearias (id)
        ON DELETE RESTRICT ON UPDATE CASCADE,

    CONSTRAINT chk_profissionais_cargo CHECK (cargo IN ('admin', 'barbeiro')),
    CONSTRAINT uq_profissionais_auth_user UNIQUE (auth_user_id),
    -- Necessário para a FK composta de agendamentos/bloqueios
    CONSTRAINT uq_profissionais_id_barbearia UNIQUE (id, barbearia_id)
);

-- =====================================================================
-- 5. TABELA: servicos
-- =====================================================================
-- O nome do serviço NÃO é globalmente único; a unicidade é por barbearia.
CREATE TABLE IF NOT EXISTS public.servicos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barbearia_id    BIGINT NOT NULL,
    nome            TEXT NOT NULL,
    descricao       TEXT,
    preco           NUMERIC(10, 2) NOT NULL,
    duracao_minutos INTEGER NOT NULL,
    ativo           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_servicos_barbearia
        FOREIGN KEY (barbearia_id) REFERENCES public.barbearias (id)
        ON DELETE RESTRICT ON UPDATE CASCADE,

    CONSTRAINT chk_servicos_preco    CHECK (preco >= 0),
    CONSTRAINT chk_servicos_duracao  CHECK (duracao_minutos > 0),
    CONSTRAINT uq_servicos_barbearia_nome UNIQUE (barbearia_id, nome),
    -- Necessário para a FK composta de agendamentos
    CONSTRAINT uq_servicos_id_barbearia UNIQUE (id, barbearia_id)
);

-- =====================================================================
-- 6. TABELA: clientes
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.clientes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barbearia_id BIGINT NOT NULL,
    nome         TEXT NOT NULL,
    telefone     TEXT,
    email        TEXT,
    observacoes  TEXT,
    ativo        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_clientes_barbearia
        FOREIGN KEY (barbearia_id) REFERENCES public.barbearias (id)
        ON DELETE RESTRICT ON UPDATE CASCADE,

    CONSTRAINT chk_clientes_email CHECK (
        email IS NULL OR email ~* '^[^@\s]+@[^@\s]+$'
    ),
    -- Necessário para a FK composta de agendamentos
    CONSTRAINT uq_clientes_id_barbearia UNIQUE (id, barbearia_id)
);

-- =====================================================================
-- 7. TABELA: horarios_funcionamento
-- =====================================================================
-- dia_semana: SMALLINT de 0 a 6.
--   0 = domingo, 1 = segunda, 2 = terça, 3 = quarta,
--   4 = quinta, 5 = sexta, 6 = sábado.
-- hora_abertura/hora_fechamento são TIME (sem fuso): rotina local da
-- barbearia, não um instante absoluto.
CREATE TABLE IF NOT EXISTS public.horarios_funcionamento (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barbearia_id    BIGINT NOT NULL,
    dia_semana      SMALLINT NOT NULL,
    hora_abertura   TIME WITHOUT TIME ZONE NOT NULL,
    hora_fechamento TIME WITHOUT TIME ZONE NOT NULL,
    fechado         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_horarios_barbearia
        FOREIGN KEY (barbearia_id) REFERENCES public.barbearias (id)
        ON DELETE RESTRICT ON UPDATE CASCADE,

    CONSTRAINT chk_dia_semana CHECK (dia_semana BETWEEN 0 AND 6),
    CONSTRAINT chk_horarios_fechamento CHECK (
        fechado OR hora_fechamento > hora_abertura
    ),
    CONSTRAINT uq_horarios_barbearia_dia UNIQUE (barbearia_id, dia_semana)
);

COMMENT ON COLUMN public.horarios_funcionamento.dia_semana IS
  '0 = domingo, 1 = segunda, 2 = terça, 3 = quarta, 4 = quinta, 5 = sexta, 6 = sábado';

-- =====================================================================
-- 8. TABELA: bloqueios_agenda
-- =====================================================================
-- Permite bloquear intervalos de data/hora (férias, almoço, reunião,
-- manutenção, feriado, ausência do barbeiro, etc.).
--   * barbeiro_id NULL  = bloqueio geral da barbearia;
--   * barbeiro_id valor = bloqueio específico de um barbeiro.
CREATE TABLE IF NOT EXISTS public.bloqueios_agenda (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barbearia_id BIGINT NOT NULL,
    barbeiro_id  BIGINT, -- NULL = bloqueio geral da barbearia
    inicio       TIMESTAMPTZ NOT NULL,
    fim          TIMESTAMPTZ NOT NULL,
    motivo       TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_bloqueios_barbearia
        FOREIGN KEY (barbearia_id) REFERENCES public.barbearias (id)
        ON DELETE RESTRICT ON UPDATE CASCADE,

    -- barbeiro_id NULL não é validado pela FK; quando preenchido, garante
    -- que o barbeiro pertence à MESMA barbearia do bloqueio.
    CONSTRAINT fk_bloqueios_barbeiro_barbearia
        FOREIGN KEY (barbeiro_id, barbearia_id)
        REFERENCES public.profissionais (id, barbearia_id)
        ON DELETE RESTRICT ON UPDATE CASCADE,

    CONSTRAINT chk_bloqueios_intervalo CHECK (fim > inicio)
);

-- =====================================================================
-- 9. TABELA: agendamentos
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.agendamentos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barbearia_id     BIGINT NOT NULL,
    cliente_id       BIGINT NOT NULL,
    barbeiro_id      BIGINT NOT NULL,
    servico_id       BIGINT NOT NULL,
    data_hora_inicio TIMESTAMPTZ NOT NULL,
    data_hora_fim    TIMESTAMPTZ NOT NULL,
    status           TEXT NOT NULL DEFAULT 'pendente',
    observacoes      TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_agendamentos_barbearia
        FOREIGN KEY (barbearia_id) REFERENCES public.barbearias (id)
        ON DELETE RESTRICT ON UPDATE CASCADE,

    -- FKs compostas abaixo FORÇAM, no nível do banco, que cliente,
    -- barbeiro e serviço pertençam à MESMA barbearia do agendamento.
    CONSTRAINT fk_agendamentos_cliente
        FOREIGN KEY (cliente_id, barbearia_id)
        REFERENCES public.clientes (id, barbearia_id)
        ON DELETE RESTRICT ON UPDATE CASCADE,

    CONSTRAINT fk_agendamentos_barbeiro
        FOREIGN KEY (barbeiro_id, barbearia_id)
        REFERENCES public.profissionais (id, barbearia_id)
        ON DELETE RESTRICT ON UPDATE CASCADE,

    CONSTRAINT fk_agendamentos_servico
        FOREIGN KEY (servico_id, barbearia_id)
        REFERENCES public.servicos (id, barbearia_id)
        ON DELETE RESTRICT ON UPDATE CASCADE,

    CONSTRAINT chk_agendamentos_status CHECK (
        status IN ('pendente', 'confirmado', 'concluido', 'cancelado')
    ),
    CONSTRAINT chk_agendamentos_intervalo CHECK (data_hora_fim > data_hora_inicio)
);

-- ---------------------------------------------------------------------
-- CONFLITO DE HORÁRIOS (EXCLUSION CONSTRAINT)
-- ---------------------------------------------------------------------
-- O banco IMPEDE que o mesmo barbeiro tenha dois agendamentos ativos
-- com intervalos sobrepostos — não depende de validação em JavaScript.
--
-- Como funciona:
--   * tstzrange(data_hora_inicio, data_hora_fim, '[)') representa o
--     intervalo [inicio, fim): o fim NÃO pertence ao intervalo, então
--     horários contíguos são permitidos.
--       PERMITIDO: 14:00-14:45 e 14:45-15:15
--       BLOQUEADO: 14:00-14:45 e 14:30-15:00
--   * O operador "&&" (sobreposição) combinado com "=" em barbeiro_id
--     exige índice GiST + extensão btree_gist (criada no item 1).
--   * A cláusula WHERE (status <> 'cancelado') faz com que agendamentos
--     cancelados NÃO bloqueiem novos horários (permite reagendar).
-- ---------------------------------------------------------------------
ALTER TABLE public.agendamentos
    ADD CONSTRAINT ux_agendamentos_sem_conflito
    EXCLUDE USING GIST (
        barbeiro_id WITH =,
        tstzrange(data_hora_inicio, data_hora_fim, '[)') WITH &&
    )
    WHERE (status <> 'cancelado');

COMMENT ON CONSTRAINT ux_agendamentos_sem_conflito ON public.agendamentos IS
  'Mantém agendamentos do mesmo barbeiro sem sobreposição; cancelados não bloqueiam';

-- =====================================================================
-- 10. TRIGGERS: atualização automática de updated_at
-- =====================================================================
CREATE TRIGGER trg_barbearias_updated_at
    BEFORE UPDATE ON public.barbearias
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_profissionais_updated_at
    BEFORE UPDATE ON public.profissionais
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_servicos_updated_at
    BEFORE UPDATE ON public.servicos
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_clientes_updated_at
    BEFORE UPDATE ON public.clientes
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_horarios_funcionamento_updated_at
    BEFORE UPDATE ON public.horarios_funcionamento
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_bloqueios_agenda_updated_at
    BEFORE UPDATE ON public.bloqueios_agenda
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_agendamentos_updated_at
    BEFORE UPDATE ON public.agendamentos
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =====================================================================
-- 11. ÍNDICES (consultas frequentes)
-- =====================================================================

-- agendamentos (as consultas mais comuns)
CREATE INDEX IF NOT EXISTS idx_agendamentos_barbearia_data
    ON public.agendamentos (barbearia_id, data_hora_inicio);
CREATE INDEX IF NOT EXISTS idx_agendamentos_barbeiro_data
    ON public.agendamentos (barbeiro_id, data_hora_inicio);
CREATE INDEX IF NOT EXISTS idx_agendamentos_cliente
    ON public.agendamentos (cliente_id);
CREATE INDEX IF NOT EXISTS idx_agendamentos_servico
    ON public.agendamentos (servico_id);
CREATE INDEX IF NOT EXISTS idx_agendamentos_status
    ON public.agendamentos (status);

-- demais entidades
CREATE INDEX IF NOT EXISTS idx_profissionais_barbearia
    ON public.profissionais (barbearia_id);
CREATE INDEX IF NOT EXISTS idx_servicos_barbearia
    ON public.servicos (barbearia_id);
CREATE INDEX IF NOT EXISTS idx_clientes_barbearia
    ON public.clientes (barbearia_id);
CREATE INDEX IF NOT EXISTS idx_horarios_barbearia
    ON public.horarios_funcionamento (barbearia_id);
CREATE INDEX IF NOT EXISTS idx_bloqueios_barbearia_inicio
    ON public.bloqueios_agenda (barbearia_id, inicio);
CREATE INDEX IF NOT EXISTS idx_bloqueios_barbeiro
    ON public.bloqueios_agenda (barbeiro_id);

-- =====================================================================
-- 12. ROW LEVEL SECURITY (RLS)
-- =====================================================================
-- Habilita RLS em todas as tabelas de negócio. Com RLS habilitado e SEM
-- policies, as roles anon/authenticated NÃO acessam nada — os dados ficam
-- protegidos por padrão. O postgres (SQL Editor/superusuário) continua
-- acessando normalmente.
ALTER TABLE public.barbearias             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profissionais          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.servicos               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clientes               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agendamentos           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.horarios_funcionamento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bloqueios_agenda       ENABLE ROW LEVEL SECURITY;

-- =====================================================================
-- ROTEIRO DE POLICIES (implementar na etapa de autenticação)
-- =====================================================================
-- IMPORTANTE: neste arquivo NÃO foi criada nenhuma policy permissiva
-- (acesso anônimo permanece bloqueado). As políticas abaixo são o
-- ROTEIRO a ser executado quando o fluxo de auth estiver pronto.
--
-- 1) Cliente público cria o próprio agendamento (role anon):
--
--    create policy "agendamentos_cliente_publico_insert"
--      on public.agendamentos
--      for insert to anon
--      with check (
--        status = 'pendente'
--        and exists (
--          select 1 from public.barbearias b
--          where b.id = agendamentos.barbearia_id and b.ativo
--        )
--        and exists (
--          select 1 from public.servicos s
--          where s.id = agendamentos.servico_id
--            and s.barbearia_id = agendamentos.barbearia_id
--            and s.ativo
--        )
--      );
--
--    Obs.: expõe apenas INSERT; os demais acessos exigem login.
--
-- 2) Usuário autenticado consulta dados da PRÓPRIA barbearia:
--
--    create policy "barbearia_read_propria" on public.barbearias
--      for select to authenticated
--      using (
--        exists (
--          select 1 from public.profissionais p
--          where p.auth_user_id = auth.uid()
--            and p.barbearia_id = barbearias.id
--            and p.ativo
--        )
--      );
--
--    (replicar para servicos, clientes, horarios_funcionamento,
--     bloqueios_agenda e agendamentos com a condição equivalente)
--
-- 3) ADMIN gerencia dados da própria barbearia:
--
--    create policy "admin_gerencia_propria_barbearia" on public.servicos
--      for all to authenticated
--      using (
--        exists (
--          select 1 from public.profissionais p
--          where p.auth_user_id = auth.uid()
--            and p.barbearia_id = servicos.barbearia_id
--            and p.cargo = 'admin' and p.ativo
--        )
--      )
--      with check (
--        exists (
--          select 1 from public.profissionais p
--          where p.auth_user_id = auth.uid()
--            and p.barbearia_id = servicos.barbearia_id
--            and p.cargo = 'admin' and p.ativo
--        )
--      );
--
--    (replicar para clientes, profissionais, horarios e bloqueios)
--
-- 4) BARBEIRO consulta e gerencia os PRÓPRIOS agendamentos:
--
--    create policy "agendamentos_barbeiro_proprios" on public.agendamentos
--      for all to authenticated
--      using (
--        barbeiro_id = (
--          select p.id from public.profissionais p
--          where p.auth_user_id = auth.uid()
--            and p.barbearia_id = agendamentos.barbearia_id
--            and p.ativo
--          limit 1
--        )
--      )
--      with check ( same condition );
--
-- =====================================================================