-- =====================================================================
-- 014 — Auditoria de eventos de segurança / administrativos
--
-- Objetivo: trilha de auditoria persistente para ações sensíveis do
-- sistema (controle de acesso de profissionais, mudanças de cargo,
-- ativação/desativação).
--
-- Escopo (Etapa 2A):
--   - Tabela public.auditorias (append-only, sem UPDATE/DELETE para
--     authenticated; sem INSERT direto — gravação via helper).
--   - Função registrar_auditoria() SECURITY DEFINER — ponto único de
--     escrita; valida que chamador é admin da barbearia.
--   - Triggers em profissionais para: ativo (ativação/desativação),
--     cargo (mudança de cargo — canal privilegiado).
--   - RLS: SELECT restrito a admin da própria barbearia.
--
-- O que NÃO é incluído nesta etapa:
--   - Auditoria de agendamentos, clientes, serviços, horários.
--   - Login/autenticação.
--   - Tela de consulta no frontend.
--
-- Execute no SQL Editor do Supabase:
--   colar e rodar este arquivo.
-- =====================================================================

-- ------------------------------------------------------------------
-- 1. Tabela: public.auditorias
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.auditorias (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barbearia_id           BIGINT NOT NULL,
    realizou_por           UUID,                      -- auth.uid() do ator (NULL = service_role/superuser)
    alvo_profissional_id   BIGINT,
    alvo_agendamento_id    BIGINT,
    alvo_cliente_id        BIGINT,
    evento                 TEXT NOT NULL,
    detalhes               JSONB,                     -- dados não-sensíveis estruturados
    ip                     TEXT,                      -- mascarado; NULL em fluxos DB-only
    created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_auditorias_barbearia
        FOREIGN KEY (barbearia_id) REFERENCES public.barbearias (id)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Índices para consultas típicas (admin vê sua barbearia, ordenado por data)
CREATE INDEX IF NOT EXISTS idx_auditorias_barbearia_created
    ON public.auditorias (barbearia_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_auditorias_alvo_profissional
    ON public.auditorias (alvo_profissional_id)
    WHERE alvo_profissional_id IS NOT NULL;

-- ------------------------------------------------------------------
-- 2. RLS: SELECT admin-only; INSERT via service_role (EFs)
-- ------------------------------------------------------------------
ALTER TABLE public.auditorias ENABLE ROW LEVEL SECURITY;

-- SELECT: admin da própria barbearia pode consultar; barbeiro NÃO.
DROP POLICY IF EXISTS auditorias_select_admin ON public.auditorias;
CREATE POLICY auditorias_select_admin
    ON public.auditorias
    FOR SELECT TO authenticated
    USING (public.usuario_e_admin_da_barbearia(barbearia_id));

-- INSERT: service_role (usado pelas Edge Functions)
-- service_role bypassa RLS por padrão, mas esta policy torna a permissão explícita.
DROP POLICY IF EXISTS auditorias_insert_service_role ON public.auditorias;
CREATE POLICY auditorias_insert_service_role
    ON public.auditorias
    FOR INSERT TO service_role
    WITH CHECK (true);

-- NENHUMA policy de UPDATE/DELETE → imutável por design.

-- Grants mínimos (defesa em profundidade):
--   * authenticated  -> SOMENTE SELECT (leitura pela política admin);
--   * service_role   -> SELECT/INSERT (gravação das Edge Functions);
--   * anon           -> nenhum privilégio.
REVOKE ALL ON TABLE public.auditorias FROM anon;
GRANT SELECT ON TABLE public.auditorias TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE public.auditorias FROM authenticated;
GRANT SELECT, INSERT ON TABLE public.auditorias TO service_role;

-- ------------------------------------------------------------------
-- 3. Função helper: registrar_auditoria (SECURITY DEFINER)
-- ------------------------------------------------------------------
-- Chamada por: Edge Functions (service_role via sql),
--              RPCs SECURITY DEFINER existentes,
--              triggers em profissionais.
--
-- Validação:
--   - Se auth.uid() existe (chamador autenticado via app): requer admin
--     da barbearia informada.
--   - Se auth.uid() é NULL (service_role/superuser): permite diretamente.
CREATE OR REPLACE FUNCTION public.registrar_auditoria(
    p_barbearia             BIGINT,
    p_evento                TEXT,
    p_detalhes              JSONB   DEFAULT NULL,
    p_alvo_profissional_id  BIGINT  DEFAULT NULL,
    p_alvo_agendamento_id   BIGINT  DEFAULT NULL,
    p_alvo_cliente_id       BIGINT  DEFAULT NULL,
    p_ip                    TEXT    DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    -- Chamador autenticado: validar que é admin da barbearia
    IF auth.uid() IS NOT NULL THEN
        IF NOT public.usuario_e_admin_da_barbearia(p_barbearia) THEN
            RAISE EXCEPTION 'sem permissão para registrar auditoria nesta barbearia';
        END IF;
    END IF;
    -- service_role / superuser: auth.uid() é NULL → permitir

    INSERT INTO public.auditorias (
        barbearia_id, realizou_por, alvo_profissional_id,
        alvo_agendamento_id, alvo_cliente_id,
        evento, detalhes, ip
    ) VALUES (
        p_barbearia,
        auth.uid(),
        p_alvo_profissional_id,
        p_alvo_agendamento_id,
        p_alvo_cliente_id,
        p_evento,
        p_detalhes,
        p_ip
    );
END;
$$;

REVOKE ALL ON FUNCTION public.registrar_auditoria(BIGINT, TEXT, JSONB, BIGINT, BIGINT, BIGINT, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.registrar_auditoria(BIGINT, TEXT, JSONB, BIGINT, BIGINT, BIGINT, TEXT) TO authenticated, service_role;

-- ------------------------------------------------------------------
-- 4. Triggers de captura em profissionais
-- ------------------------------------------------------------------

-- 4a) Exclusão soft (deleted_at) + ativação/desativação (mudança em ativo)
CREATE OR REPLACE FUNCTION public.trf_profissionais_auditoria_status()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    -- Exclusão (soft delete): registra evento dedicado.
    IF NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL THEN
        PERFORM public.registrar_auditoria(
            NEW.barbearia_id,
            'profissional_excluido',
            jsonb_build_object(
                'nome',     OLD.nome,
                'excluido', true
            ),
            NEW.id
        );
    -- Ativação / desativação.
    ELSIF NEW.ativo IS DISTINCT FROM OLD.ativo THEN
        PERFORM public.registrar_auditoria(
            NEW.barbearia_id,
            CASE WHEN NEW.ativo THEN 'profissional_ativado' ELSE 'profissional_desativado' END,
            jsonb_build_object(
                'nome',           OLD.nome,
                'ativo_anterior', OLD.ativo,
                'ativo_novo',     NEW.ativo,
                'excluido',       NEW.deleted_at IS NOT NULL
            ),
            NEW.id
        );
    END IF;
    RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.trf_profissionais_auditoria_status() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.trf_profissionais_auditoria_status() TO authenticated;

DROP TRIGGER IF EXISTS trg_profissionais_auditoria_status ON public.profissionais;
CREATE TRIGGER trg_profissionais_auditoria_status
    AFTER UPDATE OF ativo, deleted_at ON public.profissionais
    FOR EACH ROW EXECUTE FUNCTION public.trf_profissionais_auditoria_status();

-- 4b) Mudança de cargo (canal privilegiado — service_role/superuser)
CREATE OR REPLACE FUNCTION public.trf_profissionais_auditoria_cargo()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    IF NEW.cargo IS DISTINCT FROM OLD.cargo THEN
        PERFORM public.registrar_auditoria(
            NEW.barbearia_id,
            'cargo_alterado',
            jsonb_build_object(
                'nome',           OLD.nome,
                'cargo_anterior', OLD.cargo,
                'cargo_novo',     NEW.cargo
            ),
            NEW.id
        );
    END IF;
    RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.trf_profissionais_auditoria_cargo() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.trf_profissionais_auditoria_cargo() TO authenticated;

DROP TRIGGER IF EXISTS trg_profissionais_auditoria_cargo ON public.profissionais;
CREATE TRIGGER trg_profissionais_auditoria_cargo
    AFTER UPDATE OF cargo ON public.profissionais
    FOR EACH ROW EXECUTE FUNCTION public.trf_profissionais_auditoria_cargo();

-- =====================================================================
-- Notas de implementação:
--
-- - As triggers AFTER UPDATE de ativo/deleted_at/cargo são SECURITY
--   DEFINER e chamam registrar_auditoria() que INSERT bypassando RLS.
-- - A exclusão soft (admin_excluir_profissional) faz SET deleted_at =
--   now() E ativo = false na mesma UPDATE; o trigger de status detecta
--   a transição deleted_at NULL→NOT NULL e registra 'profissional_excluido'.
-- - Tentativas de mudança de cargo BLOQUEADAS pelo BEFORE trigger
--   trg_profissionais_proteger_cargo geram RAISE EXCEPTION → rollback
--   → AFTER trigger NÃO executa. Portanto, tentativas falhas de
--   alteração de cargo NÃO são registradas (limitação documentada).
-- =====================================================================
